### ISSUE TITLE
Advanced Achievements dependecy location has moved

### ISSUE THREAD

**Issue by PyvesB** [S1mple133/Matrix#2]
Hello! 👋🏻 

As a heads up, I recently moved the Advanced API dependency to JitPack. This is more reliable and easier to manage than the GitHub API branch trick I was previously using. All that is needed is changing the repository URL and the dependency information, as described in the [documentation](https://github.com/PyvesB/advanced-achievements/wiki/API).

Let me know if you bump into any issues. 😉

**Comment by d4rpx1** [comment]
Hello!

Thank you for letting us know, unfortunately we don't need the advanced achievements API anymore because the feature that used your API got removed. We might think about re-implementing it in the near future.
